---
title: "Fielding Surveys"
---

```{r}
#| echo: false

part <- "fielding-surveys"
path_slides <- file.path(part, "index.html")
path_pdf <- file.path(part, glue::glue("{part}.pdf"))
path_notes <- file.path(part, glue::glue("{part}.zip"))
```

::: {.grid}

::: {.g-col-3}

**KEYBOARD SHORTCUTS**

- Slide navigation: <kbd>←</kbd> / <kbd>→</kbd>

- Full screen: <kbd>f</kbd>

- Slide overview: <kbd>o</kbd>

- Shortcuts: <kbd>h</kbd>

:::

::: {.g-col-3}

::: {.class-buttons}

**SLIDES**

<a href=`r path_slides` class="btn-slides" target="_blank"><i class="fas fa-external-link-alt"></i> View slides</a>

<a href=`r path_pdf` class="btn-slides"><i class="fas fa-file-pdf"></i> Download PDF</a>

:::

:::

::: {.g-col-3}

::: {.class-buttons}

**RESOURCES**

<a href="https://github.com/jhelvy/formr4conjoint" class="btn-notes"><i class="fas fa-external-link-alt"></i> formr4conjoint repo</a>

<a href="https://www.jhelvy.com/posts/2021-09-18-choice-based-conjoint-surveys-in-r-with-formr/" class="btn-notes"><i class="fas fa-external-link-alt"></i> blog post</a>

<a href="https://formr.org/" class="btn-notes"><i class="fas fa-external-link-alt"></i> formr.org</a>

:::

:::

::: {.g-col-3}

::: {.class-buttons}

**PRACTICE**

<a href=`r path_notes` class="btn-notes"><i class="fas fa-download"></i> Zip file</a>

:::

:::

:::

```{r lexi-demo, echo=FALSE}
xaringanExtra::embed_xaringan(url = path_slides, ratio = "16:9")
```
