# About

This site contains content for a workshop at the [Quant UX Con 2023](https://www.quantuxcon.org/) run by [Professor John Paul Helveston](https://jhelvy.com/). 

Source files can be found at [https://github.com/jhelvy/2023-qux-conf-conjoint](https://github.com/jhelvy/2023-qux-conf-conjoint).

**Title**

An Open Source Framework for Choice Based Conjoint Experiments in R

**Summary**

Choice based conjoint (CBC) experiments are a critical tool for measuring preferences, yet most practitioners rely on closed source enterprise software to design and implement their  survey experiments. This presentation will demonstrate an open source framework for implementing CBC experiments in R. The framework includes designing and testing the experiment with the [cbcTools](https://github.com/jhelvy/cbcTools) package, implementing the survey with the [formr.org](https://formr.org/) survey platform, and modeling results with the [logitr](https://github.com/jhelvy/logitr) package. Combined, the three tools offer a free and fully open source approach to the entire CBC experiment workflow. The framework is also quite flexible and can be integrated into workflows that use enterprise software with relative ease.
