---
title: "Quant UX 2023 Workshop:"
---

# An Open Source Framework for Choice Based Conjoint Experiments in R

<hr>

John Paul Helveston

June 15, 2023

George Washington University

<hr>

# Part 1: [Introduction](parts/introduction.qmd)

In this section, we will address:

1. What is conjoint analysis?
2. Why R?
3. High-level overview of open source conjoint workflow.

# Part 2: [Designing surveys with {cbcTools}](parts/designing-surveys.qmd)

In this section, we will discuss how to use the {{< var cbcTools >}} package to design and test choice-based conjoint surveys, including:

1. Design of experiment
2. Simulating choices
3. Assessing power

# Part 3: [Estimating models with {logitr}](parts/estimating-models.qmd)

In this section, we will discuss how to use the {{< var logitr >}} package to estimate logit models on simulated data, including:

1. Mixed logit models
2. WTP space models

# Part 4: [Fielding surveys with formr](parts/fielding-surveys.qmd)

In this section, we will discuss how to use the {{< var formr >}} platform to field conjoint surveys online, including:

1. Using RMarkdown to design a survey
2. Implementing a choice-based conjoint survey in formr
